name: CI
on: [push, pull_request]

jobs:
  build-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake ninja-build
        sudo apt-get install -y libgtest-dev libbenchmark-dev
        
    - name: Configure CMake
      run: |
        cmake -B build \
              -DCMAKE_BUILD_TYPE=Release \
              -DAEC_BUILD_TESTS=ON \
              -DAEC_BUILD_BENCHMARKS=ON \
              -DAEC_BUILD_EXAMPLES=ON
    
    - name: Build
      run: cmake --build build --parallel
    
    - name: Run tests
      working-directory: build
      run: ctest --output-on-failure
    
    - name: Run benchmarks
      working-directory: build
      run: |
        ./benchmarks/aec_benchmark --benchmark_format=json > benchmark_results.json
        echo "=== BENCHMARK RESULTS ==="
        ./benchmarks/aec_benchmark --benchmark_format=console
    
    - name: Check performance
      run: |
        python3 scripts/check_performance.py build/benchmark_results.json
    
    - name: Run example
      working-directory: build
      run: |
        echo "=== EXAMPLE OUTPUT ==="
        ./examples/basic_usage

    - name: Upload benchmark results
      uses: actions/upload-artifact@v4
      with:
        name: benchmark-results
        path: build/benchmark_results.json
        retention-days: 7
